/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2015-03-09 06:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tlds/spring.tld", Long.valueOf(1425714712463L));
    _jspx_dependants.put("/WEB-INF/include.jsp", Long.valueOf(1425714711974L));
    _jspx_dependants.put("/main/../WEB-INF/tlds/splatform-btn.tld", Long.valueOf(1425714712463L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path=this.getServletContext().getContextPath();
//String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";  

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>HTML5 - Bootstrap管理后台</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<!-- basic styles -->\r\n");
      out.write("<link href=\"../static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/css/font-awesome.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/assets/css/font-awesome.min.css\" />\r\n");
      out.write("<!-- ace styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/css/ace.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/css/ace-rtl.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/css/tip-yellowsimple.css\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".border,.rain {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("/* Layout with mask */\r\n");
      out.write(".rain {\r\n");
      out.write("\tpadding: 10px 12px 12px 10px;\r\n");
      out.write("\t-moz-box-shadow: 10px 10px 10px rgba(0, 0, 0, 1) inset, -9px -9px 8px\r\n");
      out.write("\t\trgba(0, 0, 0, 1) inset;\r\n");
      out.write("\t-webkit-box-shadow: 8px 8px 8px rgba(0, 0, 0, 1) inset, -9px -9px 8px\r\n");
      out.write("\t\trgba(0, 0, 0, 1) inset;\r\n");
      out.write("\tbox-shadow: 8px 8px 8px rgba(0, 0, 0, 1) inset, -9px -9px 8px\r\n");
      out.write("\t\trgba(0, 0, 0, 1) inset;\r\n");
      out.write("\tmargin: 80px auto;\r\n");
      out.write("}\r\n");
      out.write("/* Artifical \"border\" to clear border to bypass mask */\r\n");
      out.write(".border {\r\n");
      out.write("\tpadding: 1px;\r\n");
      out.write("\t-moz-border-radius: 5px;\r\n");
      out.write("\t-webkit-border-radius: 5px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border,.rain,.border.start,.rain.start {\r\n");
      out.write("\tbackground-repeat: repeat-x, repeat-x, repeat-x, repeat-x;\r\n");
      out.write("\tbackground-position: 0 0, 0 0, 0 0, 0 0;\r\n");
      out.write("\t/* Starting Color */\r\n");
      out.write("\tbackground-color: #f7f7f7;/*#39f;*/\r\n");
      out.write("\t/* Just do something for IE-suck */\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00BA1B',\r\n");
      out.write("\t\tendColorstr='#00BA1B', GradientType=1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Non-keyframe fallback animation */\r\n");
      out.write(".border.end,.rain.end {\r\n");
      out.write("\t-moz-transition-property: background-position;\r\n");
      out.write("\t-moz-transition-duration: 30s;\r\n");
      out.write("\t-moz-transition-timing-function: linear;\r\n");
      out.write("\t-webkit-transition-property: background-position;\r\n");
      out.write("\t-webkit-transition-duration: 30s;\r\n");
      out.write("\t-webkit-transition-timing-function: linear;\r\n");
      out.write("\t-o-transition-property: background-position;\r\n");
      out.write("\t-o-transition-duration: 30s;\r\n");
      out.write("\t-o-transition-timing-function: linear;\r\n");
      out.write("\ttransition-property: background-position;\r\n");
      out.write("\ttransition-duration: 30s;\r\n");
      out.write("\ttransition-timing-function: linear;\r\n");
      out.write("\tbackground-position: -5400px 0, -4600px 0, -3800px 0, -3000px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Keyfram-licious animation */\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes colors { 0% {\r\n");
      out.write("\tbackground-color: #39f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("15%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#F246C9\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("30%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#4453F2\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("45%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#44F262\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("60%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#F257D4\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("75%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#EDF255\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("90%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#F20006\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("100%\r\n");
      out.write("{\r\n");
      out.write("background-color\r\n");
      out.write(":\r\n");
      out.write(" \r\n");
      out.write("#39f\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".border,.rain {\r\n");
      out.write("\t-webkit-animation-direction: normal;\r\n");
      out.write("\t-webkit-animation-duration: 20s;\r\n");
      out.write("\t-webkit-animation-iteration-count: infinite;\r\n");
      out.write("\t-webkit-animation-name: colors;\r\n");
      out.write("\t-webkit-animation-timing-function: ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* In-Active State Style */\r\n");
      out.write(".border.unfocus {\r\n");
      out.write("\tbackground: #fff !important;\r\n");
      out.write("\t-moz-box-shadow: 0px 0px 15px rgba(255, 255, 255, .2);\r\n");
      out.write("\t-webkit-box-shadow: 0px 0px 15px rgba(255, 255, 255, .2);\r\n");
      out.write("\tbox-shadow: 0px 0px 15px rgba(255, 255, 255, .2);\r\n");
      out.write("\t-webkit-animation-name: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rain.unfocus {\r\n");
      out.write("\tbackground: #000 !important;\r\n");
      out.write("\t-webkit-animation-name: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".margin120 {\r\n");
      out.write("\tmargin: 120px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".emp_ipt {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login-layout\" style=\"margin: 0;padding: 0;\">\r\n");
      out.write("\t<div class=\"login-container margin120 position-relative\">\r\n");
      out.write("\t\t\t<div id=\"login-box\"\r\n");
      out.write("\t\t\t\tclass=\"login-box visible widget-box no-border border start\">\r\n");
      out.write("\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"header blue lighter bigger\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-coffee green\"></i> 管理员登陆\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t<form id=\"loginForm\" name=\"loginForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset style=\"padding: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"block clearfix\" style=\"margin-bottom: 0px;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"empname\" class=\"tip-yellowsimple\" style=\"transform: scale(1, 1) translate(0px);visibility: hidden;opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tip-inner tip-bg-image\">请输入用户名</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tip-arrow tip-arrow-top tip-arrow-right tip-arrow-bottom tip-arrow-left\" style=\"visibility: inherit;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" required=\"\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Username\" id=\"usercode\" name=\"usercode\" title=\"请输入用户名\" /> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-user\"></i>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"block clearfix\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"emppwd\" class=\"tip-yellowsimple\" style=\"transform: scale(1, 1) translate(0px);visibility: hidden;opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tip-inner tip-bg-image\">请输入密码</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tip-arrow tip-arrow-top tip-arrow-right tip-arrow-bottom tip-arrow-left\" style=\"visibility: inherit;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" required=\"\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" id=\"password\" name=\"password\" title=\"请输入密码\"/> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write(" -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"emprand\" class=\"tip-yellowsimple\" style=\"opacity: 1;transform: scale(1, 1) translate(0px);visibility: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tip-inner tip-bg-image\">请输入验证码</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tip-arrow tip-arrow-left\" style=\"visibility: inherit;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"inline\" > \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"rand\" name=\"rand\" class=\"txt\" maxlength=\"4\" tabindex=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAUTOCOMPLETE=\"off\" id=\"rand\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-right: 5px; width: 66px;\" title=\"请输入验证码\"/> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img style=\"cursor: pointer;\" width=\"58\" id=\"imgCode\" height=\"21\" onclick=\"changeImg();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"width-35 pull-right btn btn-sm btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"dologin();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-key\"></i> 登陆\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"space-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /widget-body -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /position-relative -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.col -->\r\n");
      out.write("\t<div style=\"text-align: center;font-size: 20px;padding: 0 0 30px;\">\r\n");
      out.write("        \tXX技术支持,\r\n");
      out.write("        </div>\r\n");
      out.write("<!-- 提示区 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 引入js -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" lang=\"javascript\" src=\"");
      out.print(path );
      out.write("/static/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" lang=\"javascript\" src=\"");
      out.print(path );
      out.write("/static/js/jquery.mobile.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" lang=\"javascript\" src=\"");
      out.print(path );
      out.write("/static/js/jquery.poshytip.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- inline scripts related to this page -->\r\n");
      out.write("<script type=\"text/javascript\" lang=\"javascript\">\r\n");
      out.write("/* \tvar $$ = jQuery.noConflict();\r\n");
      out.write(" */\t\t\t\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \t\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/static/js/common/common.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//body onload事件处理\r\n");
      out.write("$(function(){\r\n");
      out.write("\t/**\r\n");
      out.write("\t初始化数据\r\n");
      out.write("\t*/\r\n");
      out.write("\t$('#imgCode').attr(\"title\",\"点击重新获得验证码!\");\r\n");
      out.write("\t$('#imgCode').attr(\"src\",\"");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function changeImg(){\r\n");
      out.write("\t//修改为可以点击图片切换验证码\r\n");
      out.write("\tdocument.getElementById(\"imgCode\").setAttribute(\"src\",\"");
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("?\"+new Date().getTime());\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//定义异常信息数组\r\n");
      out.write("var arrTips = [\r\n");
      out.write("'正在登陆...', //0\r\n");
      out.write("'您需要登录后才能继续浏览或操作！', //1\r\n");
      out.write("'请输入用户账号！', //2\r\n");
      out.write("'请输入密码!', //3\r\n");
      out.write("'请输入验证码!', //4\r\n");
      out.write("'验证码输入错误!', //5\r\n");
      out.write("'账号或密码不正确!请重新输入!', //6\r\n");
      out.write("'账号或密码不正确!请重新输入!', //7\r\n");
      out.write("'账号已经被锁定，请联系管理员!', //8\r\n");
      out.write("'账号已注销，请联系管理员!', //9\r\n");
      out.write("'IP异常登录!', //10\r\n");
      out.write("'您的帐户已过有效期!', //11\r\n");
      out.write("'你的密码超过30天未修改，已经被锁定！', //12\r\n");
      out.write("'对不起，你的输入数据格式不合法！', //13\r\n");
      out.write("'', //14\r\n");
      out.write("'对不起，您的密码输错五次，已经被锁定！', //15\r\n");
      out.write("'对不起，您的商户信息未找到！', //16\r\n");
      out.write("'对不起，您商户的合同已到期！', //17\r\n");
      out.write("'对不起，请确认来源地址是否正确！' //18\r\n");
      out.write("\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//登陆\r\n");
      out.write("var dologin = function(){\r\n");
      out.write("\tvar usercode = document.getElementById(\"usercode\").value;\r\n");
      out.write("\tvar password = document.getElementById(\"password\").value;\r\n");
      out.write("\tvar rand = document.getElementById(\"rand\").value;\r\n");
      out.write("\tif(usercode == '' || usercode == null){\r\n");
      out.write("\t\t$('#empname').css({'visibility':'inherit'}).fadeIn('slow');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(password == '' || password == null){\r\n");
      out.write("\t\t$('#emppwd').css({'visibility':'inherit'}).fadeIn('slow');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(rand == '' || rand == null){\r\n");
      out.write("\t\t$('#emprand').css({'visibility':'inherit'}).fadeIn('slow');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//document.getElementById(\"loginForm\").action=\"");
      if (_jspx_meth_spring_005furl_005f2(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t//document.getElementById(\"loginForm\").submit();\r\n");
      out.write("\t//ajax请求后台，处理\r\n");
      out.write("\tjQuery.ajax({\r\n");
      out.write("\t\turl: \"");
      if (_jspx_meth_spring_005furl_005f3(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("\t\tmethod:\"post\",\r\n");
      out.write("\t\tdata:{usercode:usercode,password:password,rand:rand},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tvar result = eval('(' + data + ')');\r\n");
      out.write("\t\t\t//alert(result.msg);\r\n");
      out.write("\t\t\tif(result.data == '0'){\r\n");
      out.write("\t\t\t\twindow.location='");
      out.print(path );
      out.write("/unite/index.do';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(arrTips[result.data]);\r\n");
      out.write("\t\t\t\tchangeImg();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t     /* var span_new = document.getElementById(spanName);\t\r\n");
      out.write("\t\t span_new.style.display = \"none\";\r\n");
      out.write("\t\t span_new.innerHTML = \"\"; */\r\n");
      out.write("\t   }\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t//隐藏提示\r\n");
      out.write("\t$('#usercode').focus(function(){\r\n");
      out.write("\t\t$('#empname').css({'visibility':'hidden'});\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#password').focus(function(){\r\n");
      out.write("\t\t$('#emppwd').css({'visibility':'hidden'});\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#rand').focus(function(){\r\n");
      out.write("\t\t$('#emprand').css({'visibility':'hidden'});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/*回车事件*/\r\n");
      out.write("$(\"input\").keydown(function(e){\r\n");
      out.write("\tif(e.which == 13){\r\n");
      out.write("\t\tdologin();\t\r\n");
      out.write("\t}\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f0.setParent(null);
    // /main/login.jsp(265,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f0.setValue("/authImage");
    // /main/login.jsp(265,27) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f0.setHtmlEscape("true");
    int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
      if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f1.setParent(null);
    // /main/login.jsp(270,56) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f1.setValue("/authImage");
    // /main/login.jsp(270,56) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f1.setHtmlEscape("true");
    int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
      if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f2 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f2.setParent(null);
    // /main/login.jsp(319,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f2.setValue("/system/user_login.do");
    // /main/login.jsp(319,48) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f2.setHtmlEscape("true");
    int[] _jspx_push_body_count_spring_005furl_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f2 = _jspx_th_spring_005furl_005f2.doStartTag();
      if (_jspx_th_spring_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f3 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f3.setParent(null);
    // /main/login.jsp(323,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f3.setValue("/unite/user_login.do");
    // /main/login.jsp(323,8) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f3.setHtmlEscape("true");
    int[] _jspx_push_body_count_spring_005furl_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f3 = _jspx_th_spring_005furl_005f3.doStartTag();
      if (_jspx_th_spring_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f3);
    }
    return false;
  }
}
